"""changed launcher.py file

Revision ID: f7f82869a489
Revises: 
Create Date: 2020-10-20 12:29:05.041204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7f82869a489'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('sno', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('phone_num', sa.String(length=12), nullable=False),
    sa.Column('msg', sa.String(length=120), nullable=False),
    sa.Column('date', sa.String(length=12), nullable=True),
    sa.Column('email', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('sno')
    )
    op.create_table('posts',
    sa.Column('sno', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('content', sa.String(length=120), nullable=False),
    sa.Column('tagline', sa.String(length=120), nullable=False),
    sa.Column('date', sa.String(length=60), nullable=True),
    sa.Column('img_file', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('sno')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
